title: Github Pages!
author: Morganr Developer
email: morganrdeveloper@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Aww Yiss!!! Description bruv!

# social links
twitter_username: dijuankiiing # DO NOT include the @ character, or else the build will fail!
github_username:  morganrdeveloper # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
